name: Build Valkey

on:
  workflow_dispatch:
    inputs:
      release_version:
        required: true
        type: string
      make_latest:
        required: false
        type: boolean
        default: false
      prerelease:
        required: false
        type: boolean
        default: false
    outputs:
      release_version:
        description: "The version of Valkey being built"
        value: ${{ jobs.prepare.outputs.release_version }}

jobs:
  prepare:
    runs-on: windows-latest
    outputs:
      release_version: ${{ env.RELEASE_VERSION }}
      valkey_dist: ${{ env.VALKEY_DIST }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup environment
        id: setup
        run: |
          $version = "${{ inputs.release_version }}"
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$version"
          Add-Content -Path $env:GITHUB_ENV -Value "VALKEY_DIST=Valkey-$version-Windows-x64"
          
          Invoke-WebRequest -Uri "https://github.com/valkey-io/valkey/archive/refs/tags/$version.tar.gz" -OutFile "valkey-$version.tar.gz"
          
          $releaseInfo = ConvertFrom-Json(Invoke-WebRequest -Headers @{'Authorization' = 'Bearer ${{ secrets.GITHUB_TOKEN }}'} -Uri "https://api.github.com/repos/valkey-io/valkey/releases/tags/$version").Content
          $releaseInfo.body -Replace '\#1', 'https://github.com/valkey-io/valkey/pull/1' | Set-Content .\valkey_latest_body.txt

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
  
      - name: Publish ValkeyService.exe
        run: |
          dotnet publish -c Release -r win-x64 --sc -o publish
      
      - name: Upload source and ValkeyService.exe
        uses: actions/upload-artifact@v4
        with:
          name: valkey-source
          path: |
            valkey-${{ env.RELEASE_VERSION }}.tar.gz
            valkey_latest_body.txt
            publish

  build-cygwin:
    needs: prepare
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Download source
        uses: actions/download-artifact@v4
        with:
          name: valkey-source
      
      - name: Set environment variables
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=${{ needs.prepare.outputs.release_version }}"
          Add-Content -Path $env:GITHUB_ENV -Value "VALKEY_DIST=${{ needs.prepare.outputs.valkey_dist }}"

      - name: Cache Cygwin packages
        uses: actions/cache@v4
        with:
          path: |
            C:/cygwin64
            C:/cygwin64/var/cache
          key: cygwin-${{ runner.os }}-${{ hashFiles('**/*.yml') }}
          restore-keys: cygwin-${{ runner.os }}-

      - uses: cygwin/cygwin-install-action@master
        with:
          packages: make gcc-core gcc-g++ pkg-config libssl-devel zip
          
      - name: Build Valkey with Cygwin
        env:
          CYGWIN_NOWINPATH: 1
        run: >-
          workspace=$(pwd) ;
          sed -i 's/__GNU_VISIBLE/1/' /usr/include/dlfcn.h ;
          tar -xzf valkey-${{ env.RELEASE_VERSION }}.tar.gz ;
          cd valkey-${{ env.RELEASE_VERSION }}/src && ./mkreleasehdr.sh ;
          sed -i 's/\"\;/\"/' asciilogo.h ;
          echo '" Valkey for Windows Project Home \n"' >> asciilogo.h ;
          echo '" https://github.com/valkey-io/valkey  \n\n";' >> asciilogo.h ;
          cd .. ;
          make BUILD_TLS=yes CFLAGS="-Wno-char-subscripts -O0" -j$(nproc) ;
          cd $workspace ;
          mkdir -p ${{ env.VALKEY_DIST }}-cygwin ;
          find valkey-${{ env.RELEASE_VERSION }} -mindepth 1 -maxdepth 2 -type f -regex '.*\(\.exe\|\.conf\)' -exec cp -f "{}" "${{ env.VALKEY_DIST }}-cygwin" \; ;
          cp README.md start.bat /bin/cygcrypto-3.dll /bin/cygwin1.dll /bin/cygssl-3.dll /bin/cygz.dll /bin/cyggcc_s-seh-1.dll /bin/cygstdc++-6.dll /bin/cygiconv-2.dll /bin/cygintl-8.dll ${{ env.VALKEY_DIST }}-cygwin ;
          sed -i 's/pidfile \/var\/run/pidfile ./' ${{ env.VALKEY_DIST }}-cygwin/redis.conf ;
          zip -q -r ${{ env.VALKEY_DIST }}-cygwin.zip ${{ env.VALKEY_DIST }}-cygwin ;
          cp -r ${{ env.VALKEY_DIST }}-cygwin ${{ env.VALKEY_DIST }}-cygwin-with-Service ;
          cp install_redis_service.bat uninstall_redis_service.bat publish/* ${{ env.VALKEY_DIST }}-cygwin-with-Service/ ;
          zip -q -r ${{ env.VALKEY_DIST }}-cygwin-with-Service.zip ${{ env.VALKEY_DIST }}-cygwin-with-Service
        shell: bash

      - name: Verify Cygwin version
        run: |
          $VALKEY_CYGWIN_VERSION_INFO=(./${{ env.VALKEY_DIST }}-cygwin-with-Service/redis-server.exe --version )
          echo $VALKEY_CYGWIN_VERSION_INFO
          If ( -not ( $VALKEY_CYGWIN_VERSION_INFO -match "${{ env.RELEASE_VERSION }}" ) ) { 
            Write-Output "Cygwin verification failed. Expected: ${{ env.RELEASE_VERSION }}, Got: $VALKEY_CYGWIN_VERSION_INFO"
            exit 1
          }

      - name: Test Valkey with Cygwin
        timeout-minutes: 5
        run: |
          try {
            Start-Process -NoNewWindow -FilePath ".\${{ env.VALKEY_DIST }}-cygwin-with-Service\redis-server.exe"
            Start-Sleep -Seconds 2
            $value = .\${{ env.VALKEY_DIST }}-cygwin-with-Service\redis-cli.exe SET test_key test_value
            if ($LASTEXITCODE -ne 0) { throw "Failed to set test key" }
            $value = .\${{ env.VALKEY_DIST }}-cygwin-with-Service\redis-cli.exe GET test_key
            if ($value -ne "test_value") { throw "Test failed" }
          }
          finally {
            Stop-Process -Name "redis-server" -ErrorAction SilentlyContinue
          }

      - name: Calculate hash values for Cygwin builds
        run: |
          'Cygwin Builds Hashes' | Out-File hashes-cygwin.txt
          '====================' | Out-File -Append hashes-cygwin.txt
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin.zip | Format-List | Out-File -Append hashes-cygwin.txt
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin-with-Service.zip | Format-List | Out-File -Append hashes-cygwin.txt
      
      - name: Upload Cygwin builds
        uses: actions/upload-artifact@v4
        with:
          name: valkey-cygwin-builds
          path: |
            ${{ env.VALKEY_DIST }}-cygwin.zip
            ${{ env.VALKEY_DIST }}-cygwin-with-Service.zip
            hashes-cygwin.txt

  release:
    needs: [prepare, build-cygwin]
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set environment variables
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=${{ needs.prepare.outputs.release_version }}"
          Add-Content -Path $env:GITHUB_ENV -Value "VALKEY_DIST=${{ needs.prepare.outputs.valkey_dist }}"
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      
      - name: Prepare release
        run: |
          Get-Content -Path valkey-source/valkey_latest_body.txt | Out-File -FilePath release_body.txt
          "`nHashes" | Out-File -Append -FilePath release_body.txt
          "=========" | Out-File -Append -FilePath release_body.txt
          Get-Content -Path valkey-cygwin-builds/hashes-cygwin.txt | Out-File -Append -FilePath release_body.txt
          "From workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | Out-File -Append -FilePath release_body.txt
      
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Valkey ${{ env.RELEASE_VERSION }} for Windows
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: release_body.txt
          make_latest: ${{ inputs.make_latest }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            valkey-cygwin-builds/${{ env.VALKEY_DIST }}-cygwin.zip
            valkey-cygwin-builds/${{ env.VALKEY_DIST }}-cygwin-with-Service.zip
