name: Build Valkey DIY

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Version'
        required: true
        default: "8.0.1"
        type: string
      make_latest:
        description: 'Latest'
        default: false
        type: boolean
      prerelease:
        description: 'Pre-release'
        default: false
        type: boolean
        
jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download source code
        run: |
          $tag_name="${{ github.ref_name }}"
          echo $tag_name
          (ConvertFrom-Json(Invoke-WebRequest -Headers @{'Authorization' = 'Bearer ${{ secrets.GITHUB_TOKEN }}'} -Uri "https://api.github.com/repos/valkey-io/valkey/releases/tags/$($tag_name.Trim())").Content).body -Replace '\#1', 'https://github.com/valkey-io/valkey/pull/1' | Set-Content .\valkey_latest_body.txt
          Invoke-WebRequest -Uri https://github.com/valkey-io/valkey/archive/refs/tags/$($tag_name.Trim()).tar.gz -OutFile valkey-$($tag_name.Trim()).tar.gz
          Add-Content -Path $env:GITHUB_ENV -Value "RELEASE_VERSION=$($tag_name.Trim())"
          Add-Content -Path $env:GITHUB_ENV -Value "VALKEY_DIST=Valkey-$($tag_name.Trim())-Windows-x64"

      - name: Setup dotnet
        if: ${{ success() }}
        uses: actions/setup-dotnet@v4
      - run: |
          dotnet publish -c Release -r win-x64 --sc

      - uses: cygwin/cygwin-install-action@master
        with:
          packages: make gcc-core pkg-config libssl-devel zip

      - name: cygwin Build Valkey
        env:
          CYGWIN_NOWINPATH: 1
        if: ${{ success() }}
        run: >-
          workspace=$(pwd) ;
          mkdir ${{ env.VALKEY_DIST }}-cygwin ;
          sed -i 's/__GNU_VISIBLE/1/' /usr/include/dlfcn.h ;
          rm -rf valkey-${{ env.RELEASE_VERSION }} && tar -xzf valkey-${{ env.RELEASE_VERSION }}.tar.gz ;
          echo "=== after extract ===" ;
          ls -la ;
          ls -la valkey-${{ env.RELEASE_VERSION }} || true ;
          cd valkey-${{ env.RELEASE_VERSION }}/src && pwd && ls -la ;
          ./mkreleasehdr.sh ;
          sed -i 's/\"\;/\"/' asciilogo.h ;
          echo '" Valkey for Windows Project Home \n"' >> asciilogo.h ;
          echo '" https://github.com/valkey-io/valkey  \n\n";' >> asciilogo.h ;
          cd .. ;
          make BUILD_TLS=yes CFLAGS="-Wno-char-subscripts -O0" ;
          find . -mindepth 1 -maxdepth 2 -type f -regex '.*\(\.exe\|\.conf\)' -exec cp -f "{}" "$workspace/${{ env.VALKEY_DIST }}-cygwin" \; ;
          cd $workspace ;
          cp README.md README.zh_CN.md start.bat /bin/cygcrypto-3.dll /bin/cygwin1.dll /bin/cygssl-3.dll /bin/cygz.dll /bin/cyggcc_s-seh-1.dll /bin/cygstdc++-6.dll /bin/cygiconv-2.dll /bin/cygintl-8.dll ${{ env.VALKEY_DIST }}-cygwin ;
          sed -i 's/pidfile \/var\/run/pidfile ./' ${{ env.VALKEY_DIST }}-cygwin/valkey.conf ;
          zip -q -r ${{ env.VALKEY_DIST }}-cygwin.zip ${{ env.VALKEY_DIST }}-cygwin ;
          cp install_valkey_service.bat uninstall_valkey_service.bat LICENSE Valkey.wxs publish/* ${{ env.VALKEY_DIST }}-cygwin/ ;
          mv ${{ env.VALKEY_DIST }}-cygwin ${{ env.VALKEY_DIST }}-cygwin-with-Service ;
          zip -q -r ${{ env.VALKEY_DIST }}-cygwin-with-Service.zip ${{ env.VALKEY_DIST }}-cygwin-with-Service
        shell: bash   

      - name: Verify cygwin version
        if: ${{ success() }}
        run: |
          ls
          ls ${{ env.VALKEY_DIST }}-cygwin-with-Service
          $VALKEY_CYGWIN_VERSION_INFO = ./${{ env.VALKEY_DIST }}-cygwin-with-Service/valkey-server.exe --version
          echo $VALKEY_CYGWIN_VERSION_INFO
          # If ( -not ( $VALKEY_CYGWIN_VERSION_INFO -match "${{ env.RELEASE_VERSION }}" ) ) { 
          #   Write-Output "cygwin verification failed"
          #   exit 1
          # }

      - name: Create installer
        run: |
          dotnet tool install --global wix
          ls -R ./${{ env.VALKEY_DIST }}-cygwin-with-Service
          cd ${{ env.VALKEY_DIST }}-cygwin-with-Service
          wix build Valkey.wxs -arch x64 -o ../${{ env.VALKEY_DIST }}.msi          

      - name: Calculate the hash value
        if: ${{ success() }}
        run: |
          'Hashes' | Out-File -Append .\valkey_latest_body.txt
          '=========' | Out-File -Append .\valkey_latest_body.txt          
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin.zip | Format-List
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin.zip | Format-List | Out-File -Append .\valkey_latest_body.txt
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin-with-Service.zip | Format-List
          Get-FileHash .\${{ env.VALKEY_DIST }}-cygwin-with-Service.zip | Format-List | Out-File -Append .\valkey_latest_body.txt

      - name: Add from workflow
        if: ${{ success() }}
        run: |
          "From workflow: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}" | Out-File -Append .\valkey_latest_body.txt
        
      - name: Release
        if: ${{ success() }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Valkey ${{ env.RELEASE_VERSION }} for Windows
          tag_name: ${{ env.RELEASE_VERSION }}
          body_path: valkey_latest_body.txt
          make_latest: ${{ inputs.make_latest }}
          prerelease: ${{ inputs.prerelease }}
          files: |
            ${{ env.VALKEY_DIST }}-cygwin.zip
            ${{ env.VALKEY_DIST }}-cygwin-with-Service.zip
            ${{ env.VALKEY_DIST }}.msi
